CREATE DATABASE budget
    WITH 
    OWNER = postgres
    ENCODING = 'UTF8'
    LC_COLLATE = 'C'
    LC_CTYPE = 'C'
    TABLESPACE = pg_default
    CONNECTION LIMIT = -1;


    CREATE TABLE earnings_categories
(
    earn_cat_id integer NOT NULL,
    category_name character NOT NULL,
    CONSTRAINT earnings_categories_pkey PRIMARY KEY (earn_cat_id)
)

CREATE TABLE  transactions
(
    transaction_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 25000 CACHE 1 ),
    date date,
    user_id integer,
    amount double precision,
    notes character varying COLLATE pg_catalog."default",
    type bit(1) NOT NULL,
    category_id integer,
    CONSTRAINT transactions_pkey PRIMARY KEY (transaction_id),
    CONSTRAINT earn_cat_id_fkey FOREIGN KEY (category_id)
        REFERENCES public.earnings_categories (earn_cat_id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
        NOT VALID
)
